// Halcyon injector CLI.
//
// Injects via the app.asar-replacement method — the only one current Discord's
// Electron actually loads (it ignores a `resources/app` folder when app.asar
// exists). The real `resources/app.asar` is renamed to `_app.asar`, and a small
// shim DIRECTORY takes its place as `app.asar`: the loader forces our preload,
// then boots the untouched real app from `_app.asar`. Uninstall = delete the
// shim dir and rename `_app.asar` back. The real app is never modified.

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  mkdirSync,
  writeFileSync,
  copyFileSync,
  rmSync,
  existsSync,
  statSync,
  readFileSync,
  renameSync
} from "node:fs";
import { locateInstalls, type DiscordInstall } from "./discord";
import { LOADER_JS, PRELOAD_JS, SHIM_PACKAGE_JSON } from "./templates";

const here = dirname(fileURLToPath(import.meta.url));
const payloadSource = join(here, "halcyon.js");
const MARKER = "Generated by Halcyon";

const asarPath = (i: DiscordInstall): string => join(i.resourcesPath, "app.asar");
const origPath = (i: DiscordInstall): string => join(i.resourcesPath, "_app.asar");

function isDir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}
function isFile(p: string): boolean {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

/** Our shim dir (app.asar as a directory) carries the loader marker on line 1. */
function isOurs(install: DiscordInstall): boolean {
  const idx = join(asarPath(install), "index.js");
  if (!isFile(idx)) return false;
  try {
    return readFileSync(idx, "utf8").slice(0, 200).includes(MARKER);
  } catch {
    return false;
  }
}

/** A foreign client mod (Vencord / Equicord / BetterDiscord) also turns app.asar into a dir. */
function isForeign(install: DiscordInstall): boolean {
  return isDir(asarPath(install)) && !isOurs(install);
}

function fail(message: string): never {
  console.error(`halcyon: ${message}`);
  process.exit(1);
}

function requireInstalls(): DiscordInstall[] {
  const installs = locateInstalls();
  if (!installs.length) {
    fail("no Discord installation found. Is Discord installed for the current user?");
  }
  return installs;
}
function injectOne(install: DiscordInstall, force: boolean): string {
  const asar = asarPath(install);
  const orig = origPath(install);
  if (isForeign(install) && !force) return "skipped (another client mod occupies app.asar)";

  // Preserve the real app exactly once.
  if (!existsSync(orig)) {
    if (isFile(asar)) renameSync(asar, orig);
    else return "error: app.asar missing and no _app.asar to fall back on";
  } else if (isFile(asar)) {
    // A stale app.asar file next to _app.asar (e.g. a Discord update dropped a
    // fresh asar over our removed shim); the real app already lives in _app.asar.
    rmSync(asar);
  }

  const already = isOurs(install);
  mkdirSync(asar, { recursive: true });
  writeFileSync(join(asar, "package.json"), SHIM_PACKAGE_JSON, "utf8");
  writeFileSync(join(asar, "index.js"), LOADER_JS, "utf8");
  writeFileSync(join(asar, "preload.js"), PRELOAD_JS, "utf8");
  if (existsSync(payloadSource)) copyFileSync(payloadSource, join(asar, "halcyon.js"));
  return already ? "updated" : "injected";
}

function inject(): void {
  if (!existsSync(payloadSource)) {
    fail(`payload not found at ${payloadSource}. Run \`npm run build\` first.`);
  }
  for (const install of requireInstalls()) {
    console.log(`  ${install.flavor.padEnd(20)} ${injectOne(install, false)}`);
  }
  console.log("\nDone. Fully quit Discord (from the tray) and start it again.");
}

function uninjectOne(install: DiscordInstall): string {
  const asar = asarPath(install);
  const orig = origPath(install);
  if (!isDir(asar)) return "not injected";
  if (!isOurs(install)) return "left in place (another client mod)";
  rmSync(asar, { recursive: true, force: true });
  if (existsSync(orig)) renameSync(orig, asar);
  return "removed";
}

function uninject(): void {
  for (const install of requireInstalls()) {
    console.log(`  ${install.flavor.padEnd(20)} ${uninjectOne(install)}`);
  }
  console.log("\nDone. Restart Discord to run it unmodified.");
}

function status(): void {
  const installs = locateInstalls();
  if (!installs.length) {
    console.log("no Discord installation found.");
    return;
  }
  for (const install of installs) {
    const state = isOurs(install) ? "injected" : isForeign(install) ? "other client mod" : "clean";
    console.log(`  ${install.flavor.padEnd(20)} ${state}  (${install.resourcesPath})`);
  }
}

function usage(): void {
  console.log(
    [
      "Halcyon injector",
      "",
      "usage: halcyon <command>",
      "",
      "  inject     install the shim into every detected Discord install",
      "  uninject   remove the shim, restoring Discord to stock",
      "  status     show which installs currently carry the shim",
      ""
    ].join("\n")
  );
}

const command = process.argv[2];
switch (command) {
  case "inject":
    inject();
    break;
  case "uninject":
    uninject();
    break;
  case "status":
    status();
    break;
  case undefined:
  case "help":
  case "--help":
  case "-h":
    usage();
    break;
  default:
    console.error(`halcyon: unknown command "${command}"\n`);
    usage();
    process.exit(1);
}
