// Files written into Discord's resources by the Halcyon installer / injector.
//
// Electron loads a `resources/app` directory in preference to `resources/
// app.asar`. We drop a tiny shim there: a loader that runs first, appends our
// preload to every window, and then hands control to the untouched real app
// inside app.asar. Uninstalling is just deleting the folder — app.asar is never
// modified.
//
// The renderer payload (halcyon.js) is NOT baked into the shim. The main-process
// loader refreshes it from GitHub on every launch into a stable per-user cache
// (outside resources/app, which Discord wipes on each client update), and the
// preload injects whatever is cached. That gives the desktop build the same
// auto-update behaviour the userscript gets from Tampermonkey, while a failed
// fetch or offline start simply reuses the last-good copy.
//
// IMPORTANT: keep LOADER_JS / PRELOAD_JS byte-identical to the copies embedded in
// installer/HalcyonInstaller.ps1 — both write the same shim.

/** resources/app/package.json */
export const SHIM_PACKAGE_JSON = `${JSON.stringify(
  {
    name: "halcyon-loader",
    version: "1.0.0",
    main: "index.js",
    private: true
  },
  null,
  2
)}\n`;

/** The auto-updated payload's source of truth. */
export const PAYLOAD_URL =
  "https://raw.githubusercontent.com/mzrodyu/CatieDiscordTools/main/dist/halcyon.js";

/** resources/app/index.js — runs in the Electron main process. */
export const LOADER_JS = String.raw`// Generated by Halcyon. Do not edit; run the installer's Uninstall to remove.
"use strict";

const path = require("path");
const fs = require("fs");
const os = require("os");
const https = require("https");
const electron = require("electron");

const RESOURCES = path.join(__dirname, "..");
const ASAR = path.join(RESOURCES, "app.asar");
const PRELOAD = path.join(__dirname, "preload.js");

// The auto-updated payload lives OUTSIDE resources/app: Discord installs each
// client update into a fresh app-<version> folder and orphans this shim, but a
// per-user cache dir survives that.
const PAYLOAD_URL = "https://raw.githubusercontent.com/mzrodyu/CatieDiscordTools/main/dist/halcyon.js";

function cacheDir() {
  const base =
    process.env.APPDATA ||
    (process.platform === "darwin"
      ? path.join(os.homedir(), "Library", "Application Support")
      : process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config"));
  return path.join(base, "Halcyon");
}

// Fire-and-forget refresh of the cached payload for the NEXT launch. Never blocks
// boot, never throws: the renderer always runs whatever is already cached, so a
// slow or failed fetch just means "no update this time". Deferred off the boot
// path so a stalled socket can never compete with Discord starting up.
function fetchInto(url, dest, hops) {
  const req = https.get(url, { headers: { "User-Agent": "Halcyon-Loader" } }, (res) => {
    const status = res.statusCode || 0;
    if (status >= 300 && status < 400 && res.headers.location && hops > 0) {
      res.resume();
      try {
        fetchInto(new URL(res.headers.location, url).toString(), dest, hops - 1);
      } catch (err) {
        /* bad redirect target — keep last-good cache */
      }
      return;
    }
    if (status !== 200) {
      res.resume();
      return;
    }
    const chunks = [];
    res.on("data", (c) => chunks.push(c));
    res.on("end", () => {
      try {
        const body = Buffer.concat(chunks);
        // Guard against error pages / truncated bodies clobbering a good cache.
        if (body.length < 1024) return;
        const tmp = dest + "." + process.pid + ".tmp";
        fs.writeFileSync(tmp, body);
        fs.renameSync(tmp, dest); // atomic replace on Windows (MoveFileEx)
      } catch (err) {
        /* ignore — updating is best-effort */
      }
    });
  });
  req.on("error", () => {});
  req.setTimeout(10000, () => req.destroy());
}

function refreshPayload() {
  try {
    const dir = cacheDir();
    fs.mkdirSync(dir, { recursive: true });
    fetchInto(PAYLOAD_URL, path.join(dir, "halcyon.js"), 3);
  } catch (err) {
    /* best-effort */
  }
}

setTimeout(refreshPayload, 5000);

const { BrowserWindow } = electron;

// Every renderer window gets our preload. We remember Discord's own preload so
// the preload script can chain it rather than replace it.
class HalcyonBrowserWindow extends BrowserWindow {
  constructor(options) {
    const opts = options || {};
    const webPreferences = opts.webPreferences || (opts.webPreferences = {});
    if (webPreferences.preload) {
      process.env.HALCYON_ORIGINAL_PRELOAD = webPreferences.preload;
    }
    webPreferences.preload = PRELOAD;
    super(opts);
  }
}

Object.setPrototypeOf(HalcyonBrowserWindow, BrowserWindow);

const patchedElectron = new Proxy(electron, {
  get(target, key) {
    if (key === "BrowserWindow") return HalcyonBrowserWindow;
    return target[key];
  }
});

try {
  const electronPath = require.resolve("electron");
  if (require.cache[electronPath]) {
    require.cache[electronPath].exports = patchedElectron;
  }
} catch (err) {
  console.error("[Halcyon] could not patch electron module:", err);
}

const realPackage = require(path.join(ASAR, "package.json"));
try {
  if (typeof electron.app.setAppPath === "function") electron.app.setAppPath(ASAR);
  electron.app.name = realPackage.name;
} catch (err) {
  console.error("[Halcyon] could not restore app identity:", err);
}

require(path.join(ASAR, realPackage.main));
`;

/** resources/app/preload.js — runs in each renderer before page scripts. */
export const PRELOAD_JS = String.raw`// Generated by Halcyon. Do not edit; run the installer's Uninstall to remove.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

// 1. Chain Discord's own preload so nothing it sets up is lost.
const original = process.env.HALCYON_ORIGINAL_PRELOAD;
if (original) {
  try {
    require(original);
  } catch (err) {
    console.error("[Halcyon] Discord preload failed:", err);
  }
}

// 2. Load the payload. Prefer the auto-updated cache (refreshed by the main
//    process each launch); fall back to the copy shipped next to this shim so a
//    first run with no network still works. Reading a local file keeps startup
//    instant and offline-safe — the page itself never fetches (Discord's CSP
//    would block a cross-origin fetch anyway).
function cacheFile() {
  const base =
    process.env.APPDATA ||
    (process.platform === "darwin"
      ? path.join(os.homedir(), "Library", "Application Support")
      : process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config"));
  return path.join(base, "Halcyon", "halcyon.js");
}

function readPayload() {
  const candidates = [cacheFile(), path.join(__dirname, "halcyon.js")];
  for (const p of candidates) {
    try {
      const code = fs.readFileSync(p, "utf8");
      if (code && code.length > 1024) return code;
    } catch (err) {
      // try the next candidate
    }
  }
  return null;
}

function inject() {
  const code = readPayload();
  if (!code) {
    console.error("[Halcyon] no payload available (cache empty, no bundled copy)");
    return;
  }
  const script = document.createElement("script");
  script.textContent = code + "\n//# sourceURL=halcyon://payload";
  (document.head || document.documentElement).appendChild(script);
  script.remove();
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", inject, { once: true });
} else {
  inject();
}
`;
