// Files written into Discord's resources by `halcyon inject`.
//
// Electron loads a `resources/app` directory in preference to `resources/
// app.asar`. We drop a tiny shim there: a loader that runs first, appends our
// preload to every window, and then hands control to the untouched real app
// inside app.asar. Uninstalling is just deleting the folder — app.asar is never
// modified.

/** resources/app/package.json */
export const SHIM_PACKAGE_JSON = `${JSON.stringify(
  {
    name: "halcyon-loader",
    version: "1.0.0",
    main: "index.js",
    private: true
  },
  null,
  2
)}\n`;

/** resources/app/index.js — runs in the Electron main process. */
export const LOADER_JS = String.raw`// Generated by Halcyon. Do not edit; run "halcyon uninject" to remove.
"use strict";

const path = require("path");
const electron = require("electron");

const RESOURCES = path.join(__dirname, "..");
const ASAR = path.join(RESOURCES, "app.asar");
const PRELOAD = path.join(__dirname, "preload.js");

const { BrowserWindow } = electron;

// Every renderer window gets our preload. We remember Discord's own preload so
// the preload script can chain it rather than replace it.
class HalcyonBrowserWindow extends BrowserWindow {
  constructor(options) {
    const opts = options || {};
    const webPreferences = opts.webPreferences || (opts.webPreferences = {});
    if (webPreferences.preload) {
      process.env.HALCYON_ORIGINAL_PRELOAD = webPreferences.preload;
    }
    webPreferences.preload = PRELOAD;
    super(opts);
  }
}

// Carry over static members (fromId, getAllWindows, ...).
Object.setPrototypeOf(HalcyonBrowserWindow, BrowserWindow);

const patchedElectron = new Proxy(electron, {
  get(target, key) {
    if (key === "BrowserWindow") return HalcyonBrowserWindow;
    return target[key];
  }
});

try {
  const electronPath = require.resolve("electron");
  if (require.cache[electronPath]) {
    require.cache[electronPath].exports = patchedElectron;
  }
} catch (err) {
  console.error("[Halcyon] could not patch electron module:", err);
}

// Restore the real app's identity, then boot it.
const realPackage = require(path.join(ASAR, "package.json"));
try {
  if (typeof electron.app.setAppPath === "function") electron.app.setAppPath(ASAR);
  electron.app.name = realPackage.name;
} catch (err) {
  console.error("[Halcyon] could not restore app identity:", err);
}

require(path.join(ASAR, realPackage.main));
`;

/** resources/app/preload.js — runs in each renderer before page scripts. */
export const PRELOAD_JS = String.raw`// Generated by Halcyon. Do not edit; run "halcyon uninject" to remove.
"use strict";

const fs = require("fs");
const path = require("path");

// 1. Chain Discord's own preload so nothing it sets up is lost.
const original = process.env.HALCYON_ORIGINAL_PRELOAD;
if (original) {
  try {
    require(original);
  } catch (err) {
    console.error("[Halcyon] Discord preload failed:", err);
  }
}

// 2. Inject the renderer payload into the page's main world. It must run in the
//    page context (not the isolated preload world) to reach Discord's Webpack,
//    so we add it as a <script> element.
const payloadPath = path.join(__dirname, "halcyon.js");

function inject() {
  let code;
  try {
    code = fs.readFileSync(payloadPath, "utf8");
  } catch (err) {
    console.error("[Halcyon] payload missing:", err);
    return;
  }
  const script = document.createElement("script");
  script.textContent = code + "\n//# sourceURL=halcyon://payload";
  (document.head || document.documentElement).appendChild(script);
  script.remove();
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", inject, { once: true });
} else {
  inject();
}
`;
