#Requires -Version 5.1
<#
  Halcyon Installer — one-click WinForms installer for the Halcyon Discord client mod.

  Double-click (or run the built .exe) to open the GUI: detect every Discord flavor,
  inject / repair / uninstall the loader shim, and (optionally) register a per-user
  logon task that re-injects after Discord auto-updates itself.

  The renderer payload (halcyon.js) auto-updates from GitHub on every Discord launch —
  the shim's main process refreshes a per-user cache; the installer only seeds it.

  Runtime dependencies: NONE beyond what Windows ships (.NET + WinForms + PowerShell).
  Node is NOT required to run this — it is only the developer's build-time tool.

  Silent mode:  HalcyonInstaller.exe -EnsureInjected   (used by the logon task; no GUI)
#>
param([switch]$EnsureInjected, [switch]$SelfTest)

# ============================================================================
#  Engine — pure logic, no GUI. Defined as a scriptblock so it can be both
#  dot-sourced here AND shipped verbatim into the background worker runspace.
# ============================================================================
$Engine = {
    $script:PayloadUrl     = 'https://raw.githubusercontent.com/mzrodyu/CatieDiscordTools/main/dist/halcyon.js'
    $script:Flavors        = @('Discord','DiscordPTB','DiscordCanary','DiscordDevelopment')
    $script:ProcNames      = @('Discord','DiscordPTB','DiscordCanary','DiscordDevelopment')
    $script:AppDataHalcyon = Join-Path $env:APPDATA 'Halcyon'
    $script:CacheFile      = Join-Path $script:AppDataHalcyon 'halcyon.js'
    $script:TaskName       = 'HalcyonKeepInjected'
    $script:Marker         = 'Generated by Halcyon'

    $script:ShimPackageJson = @'
{
  "name": "discord",
  "main": "index.js",
  "private": true
}
'@

    $script:ShimIndexJs = @'
// Generated by Halcyon. Do not edit; run the installer's Uninstall to remove.
"use strict";

const path = require("path");
const fs = require("fs");
const os = require("os");
const https = require("https");
const electron = require("electron");

const RESOURCES = path.join(__dirname, "..");
// The real Discord app was renamed to _app.asar; this shim IS resources/app.asar.
const ASAR = path.join(RESOURCES, "_app.asar");
const PRELOAD = path.join(__dirname, "preload.js");

// The auto-updated payload lives in a stable per-user dir: Discord installs each
// client update into a fresh app-<version> folder and discards our shim, but the
// %APPDATA%\Halcyon cache survives that.
const PAYLOAD_URL = "https://raw.githubusercontent.com/mzrodyu/CatieDiscordTools/main/dist/halcyon.js";

function cacheDir() {
  const base =
    process.env.APPDATA ||
    (process.platform === "darwin"
      ? path.join(os.homedir(), "Library", "Application Support")
      : process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config"));
  return path.join(base, "Halcyon");
}

// Fire-and-forget refresh of the cached payload for the NEXT launch. Never blocks
// boot, never throws: the renderer always runs whatever is already cached, so a
// slow or failed fetch just means "no update this time". Deferred off the boot
// path so a stalled socket can never compete with Discord starting up.
function fetchInto(url, dest, hops) {
  const req = https.get(url, { headers: { "User-Agent": "Halcyon-Loader" } }, (res) => {
    const status = res.statusCode || 0;
    if (status >= 300 && status < 400 && res.headers.location && hops > 0) {
      res.resume();
      try {
        fetchInto(new URL(res.headers.location, url).toString(), dest, hops - 1);
      } catch (err) {
        /* bad redirect target — keep last-good cache */
      }
      return;
    }
    if (status !== 200) {
      res.resume();
      return;
    }
    const chunks = [];
    res.on("data", (c) => chunks.push(c));
    res.on("end", () => {
      try {
        const body = Buffer.concat(chunks);
        // Guard against error pages / truncated bodies clobbering a good cache.
        if (body.length < 1024) return;
        const tmp = dest + "." + process.pid + ".tmp";
        fs.writeFileSync(tmp, body);
        fs.renameSync(tmp, dest); // atomic replace on Windows (MoveFileEx)
      } catch (err) {
        /* ignore — updating is best-effort */
      }
    });
  });
  req.on("error", () => {});
  req.setTimeout(10000, () => req.destroy());
}

function refreshPayload() {
  try {
    const dir = cacheDir();
    fs.mkdirSync(dir, { recursive: true });
    fetchInto(PAYLOAD_URL, path.join(dir, "halcyon.js"), 3);
  } catch (err) {
    /* best-effort */
  }
}

setTimeout(refreshPayload, 5000);

const { BrowserWindow } = electron;

// Force our preload onto Discord's real client windows — the ones that already
// carry a preload AND a title. Windows without those (splash, internal popups)
// are left untouched. NOT guarding here is one thing that breaks the window's own
// min/max/close controls; this mirrors how Vencord/Equicord patch.
class HalcyonBrowserWindow extends BrowserWindow {
  constructor(options) {
    if (!options || !options.webPreferences || !options.webPreferences.preload || !options.title) {
      super(options);
      return;
    }
    process.env.HALCYON_ORIGINAL_PRELOAD = options.webPreferences.preload;
    options.webPreferences.preload = PRELOAD;
    options.webPreferences.sandbox = false; // our preload needs fs / require
    super(options);
  }
}

// Copy the real BrowserWindow's static members and preserve its .name, then swap
// our subclass in as electron.BrowserWindow. Use a PLAIN object, NOT a Proxy: a
// Proxy over the electron module subtly breaks Discord's own window IPC and the
// min/max/close buttons stop responding. require.cache["electron"].exports is a
// getter-only accessor, so delete it before assigning.
Object.assign(HalcyonBrowserWindow, BrowserWindow);
Object.defineProperty(HalcyonBrowserWindow, "name", { value: "BrowserWindow", configurable: true });

try {
  const electronPath = require.resolve("electron");
  delete require.cache[electronPath].exports;
  require.cache[electronPath].exports = Object.assign({}, electron, { BrowserWindow: HalcyonBrowserWindow });
} catch (err) {
  console.error("[Halcyon] could not patch electron module:", err);
}

const realPackage = require(path.join(ASAR, "package.json"));
try {
  if (typeof electron.app.setAppPath === "function") electron.app.setAppPath(ASAR);
  electron.app.name = realPackage.name;
} catch (err) {
  console.error("[Halcyon] could not restore app identity:", err);
}

require(path.join(ASAR, realPackage.main));
'@

    $script:ShimPreloadJs = @'
// Generated by Halcyon. Do not edit; run the installer's Uninstall to remove.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");
const { webFrame } = require("electron");

// Discord's own preload path — chained AFTER we start the payload (below).
const original = process.env.HALCYON_ORIGINAL_PRELOAD;

// 2. Load the payload. Prefer the auto-updated cache (refreshed by the main
//    process each launch); fall back to the copy shipped next to this shim so a
//    first run with no network still works. Reading a local file keeps startup
//    instant and offline-safe — the page itself never fetches (Discord's CSP
//    would block a cross-origin fetch anyway).
function cacheFile() {
  const base =
    process.env.APPDATA ||
    (process.platform === "darwin"
      ? path.join(os.homedir(), "Library", "Application Support")
      : process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config"));
  return path.join(base, "Halcyon", "halcyon.js");
}

function readPayload() {
  const candidates = [cacheFile(), path.join(__dirname, "halcyon.js")];
  for (const p of candidates) {
    try {
      const code = fs.readFileSync(p, "utf8");
      if (code && code.length > 1024) return code;
    } catch (err) {
      // try the next candidate
    }
  }
  return null;
}

function inject() {
  const code = readPayload();
  if (!code) {
    console.error("[Halcyon] no payload available (cache empty, no bundled copy)");
    return;
  }
  // Run the payload in the page's MAIN world via webFrame.executeJavaScript. It
  // executes at document-start (before Discord's bundle, so Halcyon wins the
  // Webpack race) and is NOT subject to Discord's CSP — so, unlike a <script>
  // tag, no CSP stripping is needed. This is how Vencord/Equicord run their
  // renderer, and it avoids the CSP/Proxy tricks that broke the window controls.
  try {
    webFrame.executeJavaScript(code + "\n//# sourceURL=halcyon://payload");
  } catch (err) {
    console.error("[Halcyon] executeJavaScript failed:", err);
  }
}

inject();

// Now chain Discord's own preload so nothing it sets up is lost.
if (original) {
  try {
    require(original);
  } catch (err) {
    console.error("[Halcyon] Discord preload failed:", err);
  }
}
'@
    function Write-Utf8NoBom {
        param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Content)
        $enc = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::WriteAllText($Path, $Content, $enc)
    }

    function Test-Injected {
        # Our injection: resources/app.asar is a DIRECTORY whose index.js carries
        # the marker; the original app is preserved next to it as _app.asar.
        param([Parameter(Mandatory)][string]$ResourcesPath)
        $idx = Join-Path (Join-Path $ResourcesPath 'app.asar') 'index.js'
        if (-not (Test-Path -LiteralPath $idx)) { return $false }
        try {
            $head = Get-Content -LiteralPath $idx -TotalCount 3 -ErrorAction Stop
            return (($head -join "`n").Contains($script:Marker))
        } catch { return $false }
    }

    function Test-ForeignShim {
        # app.asar replaced by a directory that is NOT ours (Vencord/Equicord/BD).
        param([Parameter(Mandatory)][string]$ResourcesPath)
        $asar = Join-Path $ResourcesPath 'app.asar'
        $isDir = $false
        try { $ai = Get-Item -LiteralPath $asar -ErrorAction SilentlyContinue; if ($ai -and $ai.PSIsContainer) { $isDir = $true } } catch {}
        if (-not $isDir) { return $false }
        return (-not (Test-Injected -ResourcesPath $ResourcesPath))
    }

    function Get-DiscordInstalls {
        $result = @()
        $root = $env:LOCALAPPDATA
        foreach ($flavor in $script:Flavors) {
            $base = Join-Path $root $flavor
            if (-not (Test-Path -LiteralPath $base)) { continue }
            $best = $null; $bestVer = $null
            Get-ChildItem -LiteralPath $base -Directory -Filter 'app-*' -ErrorAction SilentlyContinue | ForEach-Object {
                $v = $null
                if ([version]::TryParse($_.Name.Substring(4), [ref]$v)) {
                    if ($null -eq $bestVer -or $v -gt $bestVer) { $bestVer = $v; $best = $_ }
                }
            }
            if ($null -eq $best) { continue }
            $resources = Join-Path $best.FullName 'resources'
            $asar = Join-Path $resources 'app.asar'
            $orig = Join-Path $resources '_app.asar'
            # Valid install: has app.asar (vanilla file OR a mod's directory) or our _app.asar.
            if (-not (Test-Path -LiteralPath $asar) -and -not (Test-Path -LiteralPath $orig)) { continue }
            $result += [pscustomobject]@{
                Flavor        = $flavor
                Version       = $bestVer.ToString()
                ResourcesPath = $resources
                Injected      = (Test-Injected -ResourcesPath $resources)
                OtherMod      = (Test-ForeignShim -ResourcesPath $resources)
            }
        }
        return ,$result
    }
    function Update-PayloadCache {
        # Download the latest payload into the per-user cache (atomic). $true on success.
        try {
            if (-not (Test-Path -LiteralPath $script:AppDataHalcyon)) {
                New-Item -ItemType Directory -Path $script:AppDataHalcyon -Force | Out-Null
            }
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            $wc = New-Object System.Net.WebClient
            $wc.Headers.Add('User-Agent', 'Halcyon-Installer')
            $bytes = $wc.DownloadData($script:PayloadUrl)
            $wc.Dispose()
            if ($null -eq $bytes -or $bytes.Length -lt 1024) { return $false }
            $tmp = $script:CacheFile + '.download.tmp'
            [System.IO.File]::WriteAllBytes($tmp, $bytes)
            if (Test-Path -LiteralPath $script:CacheFile) {
                [System.IO.File]::Replace($tmp, $script:CacheFile, $null)  # atomic replace
            } else {
                [System.IO.File]::Move($tmp, $script:CacheFile)
            }
            return $true
        } catch { return $false }
    }

    function Install-One {
        param([Parameter(Mandatory)]$Install, [switch]$Force)
        $res  = $Install.ResourcesPath
        $asar = Join-Path $res 'app.asar'
        $orig = Join-Path $res '_app.asar'
        if ((Test-ForeignShim -ResourcesPath $res) -and (-not $Force)) { return 'skipped-foreign' }
        $already = Test-Injected -ResourcesPath $res
        # Preserve the real app exactly once (rename app.asar -> _app.asar).
        if (-not (Test-Path -LiteralPath $orig)) {
            $ai = Get-Item -LiteralPath $asar -ErrorAction SilentlyContinue
            if ($ai -and -not $ai.PSIsContainer) { Move-Item -LiteralPath $asar -Destination $orig }
            else { return 'error: app.asar missing' }
        } else {
            # A stale app.asar file beside _app.asar — the real app is already saved.
            $ai = Get-Item -LiteralPath $asar -ErrorAction SilentlyContinue
            if ($ai -and -not $ai.PSIsContainer) { Remove-Item -LiteralPath $asar -Force }
        }
        if (-not (Test-Path -LiteralPath $asar)) { New-Item -ItemType Directory -Path $asar -Force | Out-Null }
        Write-Utf8NoBom -Path (Join-Path $asar 'package.json') -Content $script:ShimPackageJson
        Write-Utf8NoBom -Path (Join-Path $asar 'index.js')     -Content $script:ShimIndexJs
        Write-Utf8NoBom -Path (Join-Path $asar 'preload.js')   -Content $script:ShimPreloadJs
        if (Test-Path -LiteralPath $script:CacheFile) {
            try { [System.IO.File]::Copy($script:CacheFile, (Join-Path $asar 'halcyon.js'), $true) } catch {}
        }
        if ($already) { return 'updated' } else { return 'installed' }
    }

    function Uninstall-One {
        param([Parameter(Mandatory)]$Install)
        $res  = $Install.ResourcesPath
        $asar = Join-Path $res 'app.asar'
        $orig = Join-Path $res '_app.asar'
        if (-not (Test-Injected -ResourcesPath $res)) {
            if (Test-ForeignShim -ResourcesPath $res) { return 'left-foreign' }
            return 'not-present'
        }
        try {
            Remove-Item -LiteralPath $asar -Recurse -Force -ErrorAction Stop
            if (Test-Path -LiteralPath $orig) { Move-Item -LiteralPath $orig -Destination $asar }
            return 'removed'
        } catch { return ('error: ' + $_.Exception.Message) }
    }
    function Get-DiscordProcesses {
        Get-Process -ErrorAction SilentlyContinue | Where-Object { $script:ProcNames -contains $_.Name }
    }

    function Stop-DiscordProcesses {
        foreach ($p in (Get-DiscordProcesses)) { try { $p.Kill() } catch {} }
        for ($i = 0; $i -lt 25 -and (Get-DiscordProcesses); $i++) { Start-Sleep -Milliseconds 200 }
    }

    function Start-Discord {
        param([string]$Flavor = 'Discord')
        try {
            $update = Join-Path (Join-Path $env:LOCALAPPDATA $Flavor) 'Update.exe'
            if (Test-Path -LiteralPath $update) {
                Start-Process -FilePath $update -ArgumentList @('--processStart', ($Flavor + '.exe'))
            }
        } catch {}
    }

    function Get-SelfPath {
        # $PSCommandPath is populated when run as a .ps1 (dev); EMPTY inside a ps2exe
        # .exe, where the running module's file name is the exe we want to relaunch.
        if ($PSCommandPath) { return $PSCommandPath }
        try { return [System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName } catch { return $null }
    }

    function Copy-SelfToStable {
        # The re-inject task must point at a STABLE path: a portable exe run from
        # Downloads can be moved/deleted, which would silently break re-injection.
        # Copy ourselves into %LOCALAPPDATA%\Halcyon and register that copy instead.
        param([Parameter(Mandatory)][string]$SelfPath)
        try {
            $dir = Join-Path $env:LOCALAPPDATA 'Halcyon'
            if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
            $dest = Join-Path $dir (Split-Path -Leaf $SelfPath)
            if ([System.IO.Path]::GetFullPath($SelfPath) -ne [System.IO.Path]::GetFullPath($dest)) {
                [System.IO.File]::Copy($SelfPath, $dest, $true)
            }
            return $dest
        } catch { return $SelfPath }
    }

    function Register-KeepInjected {
        param([Parameter(Mandatory)][string]$SelfPath)
        $isExe = $SelfPath -match '\.exe$'
        if ($isExe) {
            $prog = $SelfPath; $argStr = '-EnsureInjected'
            $runCmd = '"' + $SelfPath + '" -EnsureInjected'
        } else {
            $prog = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
            $argStr = '-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "' + $SelfPath + '" -EnsureInjected'
            $runCmd = '"' + $prog + '" ' + $argStr
        }
        try {
            $action  = New-ScheduledTaskAction -Execute $prog -Argument $argStr
            $trigger = New-ScheduledTaskTrigger -AtLogOn
            try {
                $rep = (New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes 30)).Repetition
                $trigger.Repetition = $rep
            } catch {}
            $settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
            $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
            Register-ScheduledTask -TaskName $script:TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force -ErrorAction Stop | Out-Null
            return 'scheduled-task'
        } catch {
            try {
                New-ItemProperty -LiteralPath 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name $script:TaskName -Value $runCmd -PropertyType String -Force | Out-Null
                return 'run-key'
            } catch { return 'failed' }
        }
    }
    function Unregister-KeepInjected {
        try { Unregister-ScheduledTask -TaskName $script:TaskName -Confirm:$false -ErrorAction SilentlyContinue | Out-Null } catch {}
        try {
            $runKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
            if (Get-ItemProperty -LiteralPath $runKey -Name $script:TaskName -ErrorAction SilentlyContinue) {
                Remove-ItemProperty -LiteralPath $runKey -Name $script:TaskName -ErrorAction SilentlyContinue
            }
        } catch {}
    }

    function Invoke-EnsureInjected {
        # Silent, idempotent — for the logon task. Never kills or launches Discord.
        if (-not (Test-Path -LiteralPath $script:CacheFile)) { Update-PayloadCache | Out-Null }
        foreach ($i in (Get-DiscordInstalls)) {
            if (-not $i.Injected) { Install-One -Install $i | Out-Null }
        }
    }

    function Get-Diagnostics {
        $installs = @(Get-DiscordInstalls)
        $node = Get-Command node -ErrorAction SilentlyContinue
        if ($node) { $nodeStr = 'found (' + $node.Source + ')' } else { $nodeStr = 'not found - not required' }
        if (Test-Path -LiteralPath $script:CacheFile) {
            $kb = [math]::Round(((Get-Item -LiteralPath $script:CacheFile).Length / 1KB))
            $cacheStr = ('' + $kb + ' KB')
        } else { $cacheStr = 'none yet' }
        return ('Discord: ' + $installs.Count + '  |  PowerShell ' + $PSVersionTable.PSVersion.ToString() + '  |  Node: ' + $nodeStr + '  |  cache: ' + $cacheStr)
    }
}

# ============================================================================
#  Worker — runs inside the background runspace. Uses engine functions + $Sync.
#  (Never touches WinForms controls — the UI drains $Sync.Log on its own thread.)
# ============================================================================
$Worker = {
    function Log($m) { $Sync.Log.Enqueue([string]$m) }
    try {
        if ($Sync.Action -eq 'install') {
            $running = @()
            if ($Sync.CloseDiscord) {
                $running = @(Get-DiscordProcesses | ForEach-Object { $_.Name } | Select-Object -Unique)
                Log '正在关闭 Discord...'; Stop-DiscordProcesses
            }
            Log '正在从 GitHub 获取最新插件...'
            if (Update-PayloadCache) { Log '  插件已缓存' } else { Log '  下载失败，将使用已有缓存 / 内置副本' }
            $n = 0
            foreach ($i in (Get-DiscordInstalls)) {
                $r = Install-One -Install $i -Force:$Sync.Force
                Log ('  ' + $i.Flavor + ' ' + $i.Version + ' -> ' + $r)
                if ($r -eq 'installed' -or $r -eq 'updated') { $n++ }
            }
            if ($Sync.KeepInjected) {
                $stable = Copy-SelfToStable -SelfPath $Sync.SelfPath
                Log ('开机自动保持注入: ' + (Register-KeepInjected -SelfPath $stable))
            } else { Unregister-KeepInjected; Log '已关闭开机自动保持注入' }
            if ($Sync.CloseDiscord -and $Sync.Relaunch) {
                Log '正在重新启动 Discord...'
                if (-not $running) { $running = @('Discord') }
                foreach ($fl in $running) { Start-Discord -Flavor $fl }
            }
            $Sync.Ok = $true
            $Sync.Summary = ('完成：已注入 / 更新 ' + $n + ' 个 Discord。重启 Discord 后按 Ctrl+Shift+H 打开设置。')
        }
        elseif ($Sync.Action -eq 'uninstall') {
            $running = @()
            if ($Sync.CloseDiscord) {
                $running = @(Get-DiscordProcesses | ForEach-Object { $_.Name } | Select-Object -Unique)
                Log '正在关闭 Discord...'; Stop-DiscordProcesses
            }
            $n = 0
            foreach ($i in (Get-DiscordInstalls)) {
                $r = Uninstall-One -Install $i
                Log ('  ' + $i.Flavor + ' -> ' + $r)
                if ($r -eq 'removed') { $n++ }
            }
            Unregister-KeepInjected
            foreach ($d in @($script:AppDataHalcyon, (Join-Path $env:LOCALAPPDATA 'Halcyon'))) {
                try { if (Test-Path -LiteralPath $d) { Remove-Item -LiteralPath $d -Recurse -Force -ErrorAction SilentlyContinue } } catch {}
            }
            if ($Sync.CloseDiscord -and $Sync.Relaunch) {
                Log '正在重新启动 Discord...'
                if (-not $running) { $running = @('Discord') }
                foreach ($fl in $running) { Start-Discord -Flavor $fl }
            }
            $Sync.Ok = $true
            $Sync.Summary = ('完成：已卸载 ' + $n + ' 个。Discord 已恢复原版。')
        }
    } catch {
        $Sync.Ok = $false
        $Sync.Summary = ('出错：' + $_.Exception.Message)
        Log ('ERROR: ' + $_.Exception.Message)
    } finally {
        $Sync.Done = $true
    }
}
# ============================================================================
#  Entry
# ============================================================================
. $Engine

if ($EnsureInjected) { Invoke-EnsureInjected; return }

if ($SelfTest) {
    # Dev/CI check: exercise the engine read-only (no GUI, no injection, no network kill).
    Write-Output ('index.js chars   : ' + $script:ShimIndexJs.Length)
    Write-Output ('preload.js chars : ' + $script:ShimPreloadJs.Length)
    Write-Output ('index line 1     : ' + (($script:ShimIndexJs -split "`n")[0]).Trim())
    Write-Output ('preload line 1   : ' + (($script:ShimPreloadJs -split "`n")[0]).Trim())
    $installs = @(Get-DiscordInstalls)
    Write-Output ('discord installs : ' + $installs.Count)
    foreach ($i in $installs) { Write-Output ('  - ' + $i.Flavor + ' ' + $i.Version + ' injected=' + $i.Injected) }
    Write-Output ('diagnostics      : ' + (Get-Diagnostics))
    $tmp = Join-Path $env:TEMP 'halcyon_selftest_index.js'
    Write-Utf8NoBom -Path $tmp -Content $script:ShimIndexJs
    $b = [System.IO.File]::ReadAllBytes($tmp)
    $hasBom = ($b.Length -ge 3 -and $b[0] -eq 0xEF -and $b[1] -eq 0xBB -and $b[2] -eq 0xBF)
    Write-Output ('no-bom write OK  : ' + (-not $hasBom))
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
    return
}

# ---- GUI -------------------------------------------------------------------
# DPI awareness MUST be set before any WinForms type is loaded (ps2exe ships no
# app.manifest), or the UI renders blurry on scaled displays.
try {
    Add-Type -ErrorAction SilentlyContinue -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public static class HcDpi {
    [DllImport("shcore.dll")] public static extern int SetProcessDpiAwareness(int value);
    [DllImport("user32.dll")] public static extern bool SetProcessDPIAware();
}
"@
    try { [HcDpi]::SetProcessDpiAwareness(1) | Out-Null } catch { try { [HcDpi]::SetProcessDPIAware() | Out-Null } catch {} }
} catch {}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
[System.Windows.Forms.Application]::SetCompatibleTextRenderingDefault($false)

$Sync = [hashtable]::Synchronized(@{})
$Sync.Log = [System.Collections.Queue]::Synchronized((New-Object System.Collections.Queue))
$Sync.Done = $true

$form = New-Object System.Windows.Forms.Form
$form.Text = 'Halcyon 安装器'
$form.ClientSize = New-Object System.Drawing.Size(620, 540)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.MaximizeBox = $false
$form.Font = New-Object System.Drawing.Font('Segoe UI', 9)
$form.BackColor = [System.Drawing.Color]::White

$title = New-Object System.Windows.Forms.Label
$title.Text = 'Halcyon'
$title.Font = New-Object System.Drawing.Font('Segoe UI Semibold', 16, [System.Drawing.FontStyle]::Bold)
$title.Location = New-Object System.Drawing.Point(20, 16)
$title.AutoSize = $true
$form.Controls.Add($title)

$subtitle = New-Object System.Windows.Forms.Label
$subtitle.Text = 'Discord 桌面客户端一键安装 · 启动时自动更新'
$subtitle.ForeColor = [System.Drawing.Color]::Gray
$subtitle.Location = New-Object System.Drawing.Point(22, 50)
$subtitle.AutoSize = $true
$form.Controls.Add($subtitle)
$grid = New-Object System.Windows.Forms.DataGridView
$grid.Location = New-Object System.Drawing.Point(20, 82)
$grid.Size = New-Object System.Drawing.Size(580, 150)
$grid.ReadOnly = $true
$grid.AllowUserToAddRows = $false
$grid.AllowUserToDeleteRows = $false
$grid.RowHeadersVisible = $false
$grid.AllowUserToResizeRows = $false
$grid.SelectionMode = 'FullRowSelect'
$grid.MultiSelect = $false
$grid.AutoSizeColumnsMode = 'Fill'
$grid.BackgroundColor = [System.Drawing.Color]::White
$grid.BorderStyle = 'FixedSingle'
$col1 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn; $col1.HeaderText = 'Discord 版本'; $col1.FillWeight = 60
$col2 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn; $col2.HeaderText = '状态'; $col2.FillWeight = 40
[void]$grid.Columns.Add($col1); [void]$grid.Columns.Add($col2)
$form.Controls.Add($grid)

$chkKeep = New-Object System.Windows.Forms.CheckBox
$chkKeep.Text = '开机自动保持注入（Discord 自更新后自动重注入）'
$chkKeep.Location = New-Object System.Drawing.Point(20, 240)
$chkKeep.AutoSize = $true
$chkKeep.Checked = $true
$form.Controls.Add($chkKeep)

$btnInstall = New-Object System.Windows.Forms.Button
$btnInstall.Text = '安装 / 更新'
$btnInstall.Location = New-Object System.Drawing.Point(20, 272)
$btnInstall.Size = New-Object System.Drawing.Size(140, 34)
$form.Controls.Add($btnInstall)

$btnUninstall = New-Object System.Windows.Forms.Button
$btnUninstall.Text = '卸载'
$btnUninstall.Location = New-Object System.Drawing.Point(170, 272)
$btnUninstall.Size = New-Object System.Drawing.Size(100, 34)
$form.Controls.Add($btnUninstall)

$bar = New-Object System.Windows.Forms.ProgressBar
$bar.Style = 'Marquee'
$bar.Location = New-Object System.Drawing.Point(284, 272)
$bar.Size = New-Object System.Drawing.Size(316, 34)
$bar.Visible = $false
$form.Controls.Add($bar)

$log = New-Object System.Windows.Forms.TextBox
$log.Multiline = $true
$log.ReadOnly = $true
$log.ScrollBars = 'Vertical'
$log.Location = New-Object System.Drawing.Point(20, 316)
$log.Size = New-Object System.Drawing.Size(580, 170)
$log.Font = New-Object System.Drawing.Font('Consolas', 9)
$log.BackColor = [System.Drawing.Color]::FromArgb(248, 248, 248)
$form.Controls.Add($log)

$lblDiag = New-Object System.Windows.Forms.Label
$lblDiag.ForeColor = [System.Drawing.Color]::Gray
$lblDiag.Location = New-Object System.Drawing.Point(22, 494)
$lblDiag.Size = New-Object System.Drawing.Size(580, 36)
$form.Controls.Add($lblDiag)

$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = 120
function Append-Log([string]$t) { $log.AppendText($t + "`r`n") }

function Refresh-View {
    $grid.Rows.Clear()
    $installs = @(Get-DiscordInstalls)
    if ($installs.Count -eq 0) {
        [void]$grid.Rows.Add('未检测到 Discord', '请先安装 Discord 桌面版')
        $btnInstall.Enabled = $false
        $btnUninstall.Enabled = $false
    } else {
        foreach ($i in $installs) {
            if ($i.Injected) { $status = '已注入' }
            elseif ($i.OtherMod) { $status = '被其他 mod 占用（跳过）' }
            else { $status = '未注入' }
            [void]$grid.Rows.Add(($i.Flavor + '  ' + $i.Version), $status)
        }
        $btnInstall.Enabled = $true
        $btnUninstall.Enabled = $true
    }
    $lblDiag.Text = Get-Diagnostics
}

function Start-Worker([string]$action) {
    $close = $false; $relaunch = $false
    if (Get-DiscordProcesses) {
        $msg = "Discord 正在运行，需要关闭后重启才能生效。`n`n是 = 关闭 Discord 并在完成后自动重启`n否 = 只写入文件（下次你自己重启 Discord 生效）`n取消 = 不操作"
        $r = [System.Windows.Forms.MessageBox]::Show($msg, 'Halcyon', [System.Windows.Forms.MessageBoxButtons]::YesNoCancel, [System.Windows.Forms.MessageBoxIcon]::Question)
        if ($r -eq [System.Windows.Forms.DialogResult]::Cancel) { return }
        if ($r -eq [System.Windows.Forms.DialogResult]::Yes) { $close = $true; $relaunch = $true }
    }
    $Sync.Action = $action
    $Sync.Force = $false
    $Sync.CloseDiscord = $close
    $Sync.Relaunch = $relaunch
    $Sync.KeepInjected = $chkKeep.Checked
    $Sync.SelfPath = (Get-SelfPath)
    $Sync.Done = $false
    $Sync.Ok = $false
    $Sync.Summary = ''
    while ($Sync.Log.Count -gt 0) { [void]$Sync.Log.Dequeue() }
    $log.Clear()
    $btnInstall.Enabled = $false
    $btnUninstall.Enabled = $false
    $bar.Visible = $true
    $script:rs = [runspacefactory]::CreateRunspace()
    $script:rs.ApartmentState = 'STA'
    $script:rs.ThreadOptions = 'ReuseThread'
    $script:rs.Open()
    $script:rs.SessionStateProxy.SetVariable('Sync', $Sync)
    $script:psw = [powershell]::Create()
    $script:psw.Runspace = $script:rs
    [void]$script:psw.AddScript($Engine.ToString() + "`r`n" + $Worker.ToString())
    $script:handle = $script:psw.BeginInvoke()
    $timer.Start()
}
$timer.Add_Tick({
    while ($Sync.Log.Count -gt 0) { Append-Log ([string]$Sync.Log.Dequeue()) }
    if ($Sync.Done) {
        $timer.Stop()
        try { $script:psw.EndInvoke($script:handle) } catch {}
        try { $script:psw.Dispose() } catch {}
        try { $script:rs.Close(); $script:rs.Dispose() } catch {}
        $script:psw = $null; $script:rs = $null
        while ($Sync.Log.Count -gt 0) { Append-Log ([string]$Sync.Log.Dequeue()) }
        $bar.Visible = $false
        Refresh-View
        if ($Sync.Summary) {
            Append-Log $Sync.Summary
            if ($Sync.Ok) { $icon = [System.Windows.Forms.MessageBoxIcon]::Information }
            else { $icon = [System.Windows.Forms.MessageBoxIcon]::Error }
            [void][System.Windows.Forms.MessageBox]::Show($Sync.Summary, 'Halcyon', [System.Windows.Forms.MessageBoxButtons]::OK, $icon)
        }
    }
})

$btnInstall.Add_Click({ Start-Worker 'install' })
$btnUninstall.Add_Click({ Start-Worker 'uninstall' })

$form.Add_FormClosing({
    try { if ($script:psw) { $script:psw.Stop(); $script:psw.Dispose() } } catch {}
    try { if ($script:rs) { $script:rs.Close(); $script:rs.Dispose() } } catch {}
})

Refresh-View
Append-Log 'Halcyon 安装器就绪。点击「安装 / 更新」把插件注入 Discord 桌面版。'
[void]$form.ShowDialog()
